GLOBAL_LIST_INIT(tier1_reward, list(
	/obj/item/xenoarch/useless_relic = 5,
	/obj/item/stack/sheet/sinew = 1,
	/obj/item/stack/sheet/animalhide/goliath_hide = 1,
	/obj/item/stack/sheet/bone = 1,
	/obj/item/organ/internal/monster_core/regenerative_core/legion = 1,
))

GLOBAL_LIST_INIT(tier2_reward, list(
	/obj/item/xenoarch/broken_item/tech = 1,
	/obj/item/xenoarch/broken_item/plant = 1,
	/obj/item/xenoarch/broken_item/clothing = 1,
	/obj/item/xenoarch/broken_item/animal = 1,
	/obj/item/xenoarch/useless_relic = 5,
))

GLOBAL_LIST_INIT(tier3_reward, list(
	/obj/item/xenoarch/broken_item/weapon = 3,
	/obj/item/xenoarch/broken_item/illegal = 1,
	/obj/item/xenoarch/broken_item/alien = 1,
	/obj/item/stack/spacecash/c10000 = 1,
))



GLOBAL_LIST_INIT(tech_reward, list(
	/obj/item/pipe_dispenser = 3,
	/obj/item/construction/rcd = 3,
	/obj/item/anomaly_neutralizer = 3,
	/obj/item/megaphone = 3,
	/obj/item/bodybag/bluespace = 3,
	/obj/item/relic = 3,
	/obj/item/raw_anomaly_core/random = 3,
	/obj/item/bag_of_holding_inert = 3,
	/obj/item/construction/plumbing = 3,
	/obj/item/mmi/posibrain = 3,
	/obj/item/storage/portable_chem_mixer = 3,
	/obj/item/stock_parts/cell/crank = 3,
	/obj/vehicle/ridden/wheelchair/motorized = 3,
	/obj/vehicle/ridden/janicart = 3,
	/obj/item/stock_parts/cell/self_charge = 2,
	/obj/item/gun/medbeam = 2,
	/obj/item/crowbar/power/syndicate = 2,
	/obj/item/mod/module/holster = 2,
	/obj/item/mod/module/injector = 2,
	/obj/item/mod/module/emp_shield/advanced = 2,
	/obj/item/mod/module/visor/thermal = 2,
	/obj/item/mod/module/visor/night = 2,
	/obj/item/mod/module/springlock/bite_of_87 = 2,
	/obj/item/multitool/ai_detect = 2,
	/obj/item/mod/module/chameleon = 2,
	/obj/item/mod/module/plate_compression = 2,	
	/obj/item/mod/module/noslip = 2,
	/obj/item/autosurgeon/syndicate/anti_stun 1,
	/obj/item/storage/box/syndie_kit/imp_microbomb = 1,	
	/obj/item/autosurgeon/syndicate/reviver = 1,
	/obj/item/autosurgeon/syndicate/thermal_eyes = 1,
	/obj/machinery/vending/magivend = 1,
))

GLOBAL_LIST_INIT(weapon_reward, list(
	/obj/item/spear/bonespear = 6,
	/obj/item/gun/ballistic/bow/tribalbow/ashen = 5,
	/obj/item/ammo_casing/arrow/ash = 5,
	/obj/item/claymore/cutlass = 5,
	/obj/item/shield/roman = 53,
	/obj/item/gun/ballistic/automatic/pistol/toy/riot = 3,
	/obj/item/gun/ballistic/automatic/c20r/toy = 3,
	/obj/item/gun/ballistic/automatic/l6_saw/toy = 3,
	/obj/item/shield/riot = 3,
	/obj/item/pneumatic_cannon = 3,
	/obj/item/storage/box/syndie_kit/throwing_weapons = 2,
	/obj/item/borg/upgrade/modkit/indoors = 2,
	/obj/item/gun/ballistic/automatic/pistol = 2,
	/obj/item/gun/syringe/rapidsyringe = 2,
	/obj/item/gun/syringe/dna = 2,
	/obj/item/gun/magic/hook = 2,
	/obj/item/gun/syringe/syndicate = 2,
	/obj/item/gun/ballistic/automatic/plastikov = 2,
	/obj/item/gun/energy/recharge/ebow = 2,
	/obj/machinery/vending/toyliberationstation = 1,
	/obj/item/melee/energy/sword/saber = 1,
	/obj/item/gun/ballistic/revolver/syndicate = 1,
	/obj/item/storage/box/hug/reverse_revolver = 1,
	/obj/item/grenade/syndieminibomb = 1,
	/obj/item/autosurgeon/syndicate/laser_arm = 1,
	/obj/item/gun/ballistic/shotgun/bulldog = 1,
))

GLOBAL_LIST_INIT(clothing_reward, list(
	/obj/item/clothing/gloves/military/ashwalk = 1,
	/obj/item/clothing/gloves/military/claw = 1,
	/obj/item/clothing/head/shamanash = 1,
	/obj/item/clothing/shoes/jackboots/ashwalker = 1,
	/obj/item/clothing/shoes/jackboots/ashwalker/legate = 1,
	/obj/item/clothing/shoes/wraps/ashwalker = 1,
	/obj/item/clothing/suit/ashwalkermantle = 1,
	/obj/item/clothing/suit/ashwalkermantle/cape = 1,
	/obj/item/clothing/under/costume/gladiator/ash_walker/greentrib = 1,
	/obj/item/clothing/under/costume/gladiator/ash_walker/yellow = 1,
	/obj/item/clothing/under/costume/gladiator/ash_walker/chiefrags = 1,
	/obj/item/clothing/under/costume/gladiator/ash_walker/shaman = 1,
	/obj/item/clothing/under/costume/gladiator/ash_walker/robe = 1,
	/obj/item/clothing/under/costume/gladiator/ash_walker/tribal = 1,
	/obj/item/clothing/under/costume/gladiator/ash_walker/white = 1,
	/obj/item/clothing/neck/necklace/ashwalker = 1,
	/obj/item/clothing/head/helmet/gladiator = 1,
	/obj/item/clothing/under/costume/gladiator/ash_walker = 1,
))

GLOBAL_LIST_INIT(illegal_reward, list(
	/obj/item/stack/telecrystal = 5,
	/obj/item/storage/toolbox/syndicate = 4,
	/obj/item/storage/toolbox/mechanical/old/clean = 4,
	/obj/item/storage/fancy/cigarettes/cigpack_syndicate = 4,
	/obj/item/soap/syndie = 4,
	/obj/item/book/bible/syndicate = 4,
	/obj/item/storage/box/syndie_kit/cutouts = 4,
	/obj/item/storage/box/syndie_kit/stickers = 4,
	/obj/item/disk/nuclear/fake = 4,
	/obj/item/card/id/advanced/chameleon = 4,
	/obj/item/suppressor = 3,
	/obj/item/toy/plush/carpplushie/dehy_carp = 3,
	/obj/item/stack/sticky_tape/pointy/super = 3,
	/obj/item/storage/box/rndboards = 3,
	/obj/item/chameleon = 3,
	/obj/item/camera_bug = 3,
	/obj/item/storage/backpack/duffelbag/syndie/surgery = 3,
	/obj/item/toy/balloon/syndicate = 3,
	/obj/item/jammer = 3,
	/obj/item/guardiancreator/tech/choose/traitor = 2,
	/obj/item/encryptionkey/syndicate = 2,
	/obj/item/encryptionkey/binary = 2,
	/obj/item/clothing/glasses/thermal/syndi = 2,
	/obj/item/storage/briefcase/launchpad = 2,
	/obj/item/storage/box/syndie_kit/syndicate_teleporter = 2,
	/obj/item/card/emag/doorjack = 2,
	/obj/item/card/emag = 2,
	/obj/item/suspiciousphone = 2,
	/obj/item/storage/box/syndie_kit/imp_stealth = 2,
	/obj/item/storage/box/syndie_kit/imp_storage = 2,
	/obj/item/mod/control/pre_equipped/traitor = 2,
	/obj/item/mod/control/pre_equipped/traitor_elite = 1,
	/obj/vehicle/ridden/speedwagon = 1,
))

GLOBAL_LIST_INIT(plant_reward, list(
	/obj/item/food/grown/gelthi = 1,
	/obj/item/seeds/random = 1,
	/obj/item/food/grown/amauri = 1,
	/obj/item/food/grown/jurlmah = 1,
	/obj/item/food/grown/nofruit = 1,
	/obj/item/food/grown/shand = 1,
	/obj/item/food/grown/surik = 1,
	/obj/item/food/grown/telriis = 1,
	/obj/item/food/grown/thaadra = 1,
	/obj/item/food/grown/vale = 1,
	/obj/item/food/grown/vaporsac = 1,
))

GLOBAL_LIST_INIT(animal_reward, list(
	/obj/item/stack/sheet/sinew = 4,
	/obj/item/stack/sheet/animalhide/goliath_hide = 4,
	/obj/item/stack/sheet/bone = 4,
	/obj/item/organ/internal/monster_core/regenerative_core/legion = 4,
	/mob/living/simple_animal/pet/cat/breadcat = 1,
	/mob/living/simple_animal/pet/gondola = 1,
))

GLOBAL_LIST_INIT(alien_reward, list(
	/obj/item/wrench/abductor = 1,
	/obj/item/wirecutters/abductor = 1,
	/obj/item/weldingtool/abductor = 1,
	/obj/item/screwdriver/abductor = 1,
	/obj/item/crowbar/abductor = 1,
	/obj/item/multitool/abductor = 1,
	/obj/item/scalpel/alien = 1,
	/obj/item/hemostat/alien = 1,
	/obj/item/retractor/alien = 1,
	/obj/item/circular_saw/alien = 1,
	/obj/item/surgicaldrill/alien = 1,
	/obj/item/cautery/alien = 1,
))
